"""Añadir opens_at, closes_at, created_at, updated_at a Store con server_default

Revision ID: 1ff6f54b2c47
Revises: 63073d3c3c46
Create Date: 2025-05-13 13:56:40.340192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff6f54b2c47'
down_revision = '63073d3c3c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opens_at', sa.Time(), server_default='00:00:00', nullable=False))
        batch_op.add_column(sa.Column('closes_at', sa.Time(), server_default='00:00:00', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('closes_at')
        batch_op.drop_column('opens_at')

    # ### end Alembic commands ###
