"""Added Store model

Revision ID: 38487449585f
Revises: d7c289b2ae6c
Create Date: 2025-03-12 15:45:41.250671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38487449585f'
down_revision = 'd7c289b2ae6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=240), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('logo', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('nit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    # ### end Alembic commands ###
