"""Added Area model with foreign key to Zone

Revision ID: 487a34045740
Revises: bf62790fd88a
Create Date: 2025-03-11 12:01:56.542253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487a34045740'
down_revision = 'bf62790fd88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=150), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.zone_id'], ),
    sa.PrimaryKeyConstraint('area_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area')
    # ### end Alembic commands ###
