"""new field for order

Revision ID: 4e3a4579fb27
Revises: 4e56b7c80641
Create Date: 2025-03-21 21:08:50.857783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3a4579fb27'
down_revision = '4e56b7c80641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
