"""quantity in product cart

Revision ID: 4e56b7c80641
Revises: 2e8a8437bba6
Create Date: 2025-03-20 09:15:50.461235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e56b7c80641'
down_revision = '2e8a8437bba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_product', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
