"""product_received entity

Revision ID: 4f372b6b428c
Revises: bc9790710746
Create Date: 2025-05-10 19:33:04.549036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f372b6b428c'
down_revision = 'bc9790710746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_received',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_string', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_received')
    # ### end Alembic commands ###
