"""Added UserRating model

Revision ID: 52300d3d20d8
Revises: c66034dc777b
Create Date: 2025-03-18 10:28:56.126210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52300d3d20d8'
down_revision = 'c66034dc777b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rating',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rating')
    # ### end Alembic commands ###
