"""fix

Revision ID: 63073d3c3c46
Revises: 35108122efee
Create Date: 2025-04-25 23:59:43.332653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63073d3c3c46'
down_revision = '4e3a4579fb27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_events',
    sa.Column('attempt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signup_events')
    # ### end Alembic commands ###
