"""Added Cart model

Revision ID: 748ee9d7ff3f
Revises: 52300d3d20d8
Create Date: 2025-03-18 11:17:14.368319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748ee9d7ff3f'
down_revision = '52300d3d20d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAYMENT_PROGRESS', 'BILLED', 'DISABLED', name='cart_status_enum'), nullable=False),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
