"""Added new model for product

Revision ID: 75b1aaffec87
Revises: cfed04b106a9
Create Date: 2025-03-12 17:47:32.146477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b1aaffec87'
down_revision = 'cfed04b106a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('product_type', sa.Enum('PRODUCT', 'SUBSCRIPTION', name='product_type_enum'), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('detail', sa.String(length=240), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
