"""Updated User and Cart models to include Order relationship

Revision ID: 82047d374050
Revises: ec677c7ed584
Create Date: 2025-03-18 17:36:06.015371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82047d374050'
down_revision = 'ec677c7ed584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAYMENT_PROGRESS', 'BILLED', 'DISABLED', name='status_enum'), nullable=False),
    sa.Column('billed_date', sa.Date(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
