"""ajuste del backend

Revision ID: 9888365c25c8
Revises: 35108122efee
Create Date: 2025-05-15 19:57:39.646249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9888365c25c8'
down_revision = '35108122efee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('product_received',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_string', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('store_count',
    sa.Column('store_count_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('store_count_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_count')
    op.drop_table('product_received')
    op.drop_table('location')
    # ### end Alembic commands ###
