"""ajuste store

Revision ID: be176fb40952
Revises: 9888365c25c8
Create Date: 2025-05-15 20:18:45.362552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be176fb40952'
down_revision = '9888365c25c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opens_at', sa.Time(), server_default='00:00:00', nullable=False))
        batch_op.add_column(sa.Column('closes_at', sa.Time(), server_default='00:00:00', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('closes_at')
        batch_op.drop_column('opens_at')

    # ### end Alembic commands ###
