"""Reinitializing database

Revision ID: bf62790fd88a
Revises: 
Create Date: 2025-03-11 09:42:18.924808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf62790fd88a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('zone_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone')
    # ### end Alembic commands ###
