"""Updated User model to use ENUM for user_type

Revision ID: e83caecdb877
Revises: 487a34045740
Create Date: 2025-03-11 14:39:48.943467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83caecdb877'
down_revision = '487a34045740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('user_email', sa.String(length=240), nullable=False),
    sa.Column('mobile_number', sa.String(length=60), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Enum('CUSTOMER', 'DELIVERY', 'STORE', name='user_type_enum'), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.area_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
