INSERT INTO area (area_name, zone_id) VALUES
('Historic Center', 1),
('Financial District', 1),
('Downtown', 2),
('Residential Area', 2),
('Beachfront', 3),
('Tourist Zone', 3),
('University Campus', 4),
('Technology Park', 4),
('Industrial Zone', 5),
('Shopping Mall Area', 5),
('Cultural District', 6),
('Entertainment Hub', 6),
('Medical District', 7),
('Sports Complex', 7),
('Green Park', 8),
('Residential Towers', 8),
('Harbor Area', 9),
('Old Town', 9),
('Airport Zone', 10),
('Business Center', 10);
